In [3]:
from musicpy import *
import numpy as np
import time

In [72]:
def findparas(points, listtype):
    sort_point = points[np.argsort(points[:,0])]
    unique_points = points[np.unique(points[:,0]//20,axis=0,return_index=True)[1]]
    x = unique_points[:,0]//20
    y = unique_points[:,1]
    timelist = np.zeros(50)
    chordlist = []
    for i in set(x):
        timelist[i] = 1
    onesrange = np.argwhere(timelist == 1).flatten()
    starttime = onesrange[0]
    intervallist = np.zeros(len(onesrange))
    for i in range(len(onesrange)):
        if i!=len(onesrange)-1:
            intervallist[i] = onesrange[i+1]-onesrange[i]
        else:
            intervallist[i] = 50-onesrange[i]
    for yval in y:
        chordlist.append(decideNote(yval, listtype))
    return starttime, intervallist.tolist(), chordlist
def decideNote(y, listtype):
    classy = 0
    interval = 100/7
    octave = 6- y//100
    y = y%100
    for i in range(1,7):
        if y>=interval*i and y<=interval*(i+1):
            classy = i
    return listtype[classy]+str(octave)
### checkpoint
majorChordList = ["C", "D", "E", "F", "G", "A", "B"]
decideNote(0, majorChordList)

'C6'

In [ ]:
def play_button_event(): #play piece
    trackTotal = [C1, C2, C3, C4, C5]
    instrumentTotal = [20, 25, 46, 108, 109]
    
    my_piece = piece(tracks = tracklist, instruments = instrumentlist, bpm = 120, start_times = startTimelist)
    play(my_piece)


button_play = Button(root, text="Play your music", height=1, width=20, bg='white', command=lambda:play_button_event())
button_play_window = canvas.create_window(500+button_offset, 350, anchor=NW, window=button_play)

In [51]:
C1 = chord(['C5','E5', 'G5', 'B5'], interval=[0.5, 0.5, 0, 2], duration=[1, 2, 0.5, 1])
C2 = (chord('C2, C2, G1, G1') % (1,1)) % 2
C3 = (chord('F#6, G6') % (1/8, 1/8) % 8 | chord('A5, B5') % (1/8, 1/8) % 8) % 2
C4 = (chord('G3, G3, G3, G3') % ([3/8,1/8,1/4,1/4], [3/8,1/8,1/4,1/4]) % 4)

new_piece = piece(tracks=[C1, C2, C3, C4],
                  instruments=[11, 'Electric Bass (finger)', 'Orchestral Harp', 'Synth Drum'],
                  bpm=120,
                  start_times=[0, 2, 2, 6])
play(new_piece)

In [7]:
play(chord(['C5','E5', 'G5', 'B5'], interval=[0.5, 0.5, 0, 2], duration=[1, 2, 0.5, 1]))

|  No  | Instrument  |
| ---- | ---- |
|  20  | Church Organ |
|  25  | Acoustic Guitar (steel) |
|  46  | Orchestral Harp |
|  108 | Kalimba |
|  109 | Bagpipe |
|  123 | Bird Tweet| 


In [6]:
play(note("E#"))

ValueError: Invalid note name 'E#', accepted note names are ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'Bb', 'Eb', 'Ab', 'Db', 'Gb', 'c', 'c#', 'd', 'd#', 'e', 'f', 'f#', 'g', 'g#', 'a', 'a#', 'b', 'bb', 'eb', 'ab', 'db', 'gb']

In [77]:
np.array([[1,2]])

array([[1, 2]])

In [75]:
points = np.array([[100,3],
                [40,100], 
                [21,120],
                [39,20],
                [44,20],
                [50,20],
                [140,20],
                [79,20]])
start_time, intervallist, chordnotelist = findparas(points, majorChordList)
chordnotelist

['D5', 'C5', 'D6', 'C6', 'D6']

In [61]:
for i in points[:,1]:
    print(decideNote(i, majorChordList))

C6
C5
D5
D6
D6
D6
D6
D6


In [4]:
sort_point = points[np.argsort(points[:,0])]
sort_point

array([[ 21, 120],
       [ 39,  20],
       [ 40, 100],
       [ 44,  20],
       [ 50,  20],
       [ 79,  20],
       [100,   3],
       [140,  20]])

In [10]:
x = sort_point[:,0]//20
timelist = np.zeros(50)
for i in set(x):
    timelist[i] = 1
timelist

array([0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
onesrange = np.argwhere(timelist == 1).flatten()
starttime = onesrange[0]
onesrange

array([1, 2, 3, 5, 7])

In [24]:
intervallist = np.zeros(len(onesrange))
for i in range(len(onesrange)):
    if i!=len(onesrange)-1:
        intervallist[i] = onesrange[i+1]-onesrange[i]
    else:
        intervallist[i] = 50-onesrange[i]
intervallist

array([ 1.,  1.,  2.,  2., 43.])

In [29]:
play(chord(["C", "D", "E", "F", "G"], interval = intervallist.tolist()))

In [22]:
list[interval]

list[array([ 1.,  1.,  2.,  2., 43.])]

---
don't need

In [ ]:
# generating notes
majorNoteList = ["C", "D", "E", "F", "G", "A", "B"]
def ytoNote(y, listtype, volume = 100):
    classy = 0
    interval = 100/7
    if y <= 100: # pitch = 4
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return note(listtype[classy], 5, 1, volume)
    else: # pitch = 5
        y = y-100
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return note(listtype[classy], 4, 1, volume)
def play_note(y, listtype, brush, volume = 100): # center (x, y), y <= 200, brush = instrument type
    play(ytoNote(y, listtype, volume), instrument = brush)
# generating chords
majorChordList = ["C", "Dm", "Em", "F", "G", "Am", "Bdim"]
def ytoChord(y, listtype):
    classy = 0
    interval = 100/7
    if y <= 300: # pitch = 4
        y -= 200
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return C(listtype[classy], 4, 1/4, 1/8)
    else: # pitch = 5
        y = y-300
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return C(listtype[classy], 3, 1/4, 1/8)
def play_chord(y, listtype, brush, volume = 100): # center (x, y), y>200, brush = instrument type
    c = ytoChord(y, listtype)
    c.setvolume(volume)
    play(c, instrument=brush)
# combine together
def play_sound(y, brush, volume):
    if y <=200:
        play_note(y, majorNoteList, brush, volume)
    else:
        play_chord(y, majorChordList, brush, volume)

In [8]:
majorNoteList = ["C", "D", "E", "F", "G", "A", "B"]
def ytoNote(y, listtype, volume = 100):
    classy = 0
    interval = 100/7
    if y <= 100: # pitch = 4
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = i
        return note(listtype[classy], 4, 1, volume)
    else: # pitch = 5
        y = y-100
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = i
        return note(listtype[classy], 5, 1, volume)
def play_note(y, listtype, brush, volume = 100): # center (x, y), y <= 200, brush = instrument type
    play(ytoNote(y, listtype, volume), instrument = brush)

majorNoteList = ["C", "D", "E", "F", "G", "A", "B"]
timelist = [0]*50
trackchordlist = []
def ytoNoteTrack(x, y, listtype):
    timelist[x//20] = 1
    classy = 0
    interval = 100/7
    if y <= 100: # pitch = 4
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = i
        trackchordlist.append(listtype[classy])
    else: # pitch = 5
        y = y-100
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = i
        trackchordlist.append(listtype[classy])
def play_track_note(x, y, listtype, brush, volume = 100): # center (x, y), y <= 200, brush = instrument type
    play(ytoNote(y, listtype, volume), instrument = brush)

In [7]:
play_note(y = 60, listtype = majorNoteList, brush = 108, volume = 100)

In [8]:
majorChordList = ["C", "Dm", "Em", "F", "G", "Am", "Bdim"]
def ytoChord(y, listtype):
    classy = 0
    interval = 100/7
    if y <= 300: # pitch = 4
        y -= 200
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return C(listtype[classy], 4, 1/4, 1/8)
    else: # pitch = 5
        y = y-300
        for i in range(1,7):
            if y>=interval*i and y<=interval*(i+1):
                classy = 7-i
        return C(listtype[classy], 5, 1/4, 1/8)
def play_chord(y, listtype, brush, volume = 100): # center (x, y), y>200, brush = instrument type
    c = ytoChord(y, listtype)
    c.setvolume(volume)
    play(c, instrument=brush)

In [9]:
play_chord(210.35, majorChordList, 46, 100)

In [10]:
def play_sound(y, brush, volume):
    if y <=200:
        play_note(y, majorNoteList, brush, volume)
    else:
        play_chord(y, majorChordList, brush, volume)

In [11]:
play_sound(208, 108, 100)

In [12]:
guitar = (C('CM7', 3, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2 |
          C('A7sus', 2, 1/4, 1/8)^2 |
          C('Em7', 2, 1/4, 1/8)^2 | 
          C('FM7', 2, 1/4, 1/8)^2 |
          C('CM7', 3, 1/4, 1/8)@1 |
          C('AbM7', 2, 1/4, 1/8)^2 |
          C('G7sus', 2, 1/4, 1/8)^2)

play(guitar, bpm=100, instrument=46)

|1|2|3|4|5|6|7|8|9|10|11|12|
| - | - | - | - | - | - | - | - | - | - | - | - |
|C|C#|D|D#|E|F|F#|G|G#|A|A#|B|
|C|Db|D|Eb|E|F|Gb|G|Ab|A|Bb|B|


# Basic Logic
## Painting Algorithms
### Brushes type and timbres
+ If `circle brush`, `timbre = 46 (Orchestral Harp)`
+ If `Square brush`, `timbre = 109 (Bagpip)`
+ If `line brush`, `timbre = 25 (Acoustic Guitar)`
+ If `star brush`, `timbre = 108 (Kalimba)`
+ If `polygon brush`, `timbre = 20 (Church Organ)`
+ If `random`, `timbre = 123 Bird Tweet`
### Brushes size and volume
smaller size, lower volume
### Pitches and paintings
Pitches Note: change according to x, y positions

## Music Algorithms
### Key control
+ Key restrict mode: When choorse corresponding key, only seven notes can be played.
+ Nonrestriction mode: No key restrictions
